[versions]
gradle-shadow = "9.3.1"
jda = "6.3.0"
slf4j = "2.0.17"
guava = "33.5.0-jre"
lang3 = "3.20.0"
gson = "2.13.2"
hytale = "2026.01.22-6f8bdbdc4"
paper = "1.21.11-R0.1-SNAPSHOT"
shodo = "1.1.0-SNAPSHOT"

[libraries]
jda = { group = "net.dv8tion", name = "JDA", version.ref = "jda" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "lang3" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
hytale = { group = "com.hypixel.hytale", name = "Server", version.ref = "hytale" }
paper-api = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
shodo = { group = "cc.irori", name = "shodo", version.ref = "shodo" }

[plugins]
gradle-shadow = { id = "com.gradleup.shadow", version.ref = "gradle-shadow" }