BotToken: "YOUR_TOKEN_HERE"
ChatChannelId: "YOUR_CHANNEL_ID_HERE"
UseJapanize: true
JoinMessageFormat: "**{PLAYER}** has joined the game."
QuitMessageFormat: "**{PLAYER}** has left the game."
ChatMessageFormat: "**{PLAYER}**: {MESSAGE}"
ChatMessageFormatJapanize: "**{PLAYER}**: {MESSAGE} (`{JAPANESE}`)"